version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - ./db_init/init_db:/docker-entrypoint-initdb.d

  application:
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      ENTITY_COLLECTION: "entity"
      USER_COLLECTION: "user"
      APP_MONGO_DB: "app"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      SESSION_COLLECTION: "session"
      IMAGE_COLLECTION: "image"
      SECRET_KEY: ""
      REDIS_URL: "redis:6379"
      TIME_LIVE_MINUTE_JWT: 1000
      TIME_EXPIRED_CACHE_MINUTE: 1
    ports:
      - "8005:8000"
    depends_on:
      - postgres

  mongo:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      APP_MONGO_DB: "app"

  redis:
    image: redis
    ports:
      - "6379:6379"