version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
    ports:
      - "5433:5432"


  application:
    build:
      context: ./
      dockerfile: dockerfile
    environment:
      USED_DB: "pg"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      ENTITY_COLLECTION: "entity"
      USER_COLLECTION: "user"
      APP_MONGO_DB: "app"
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      SESSION_COLLECTION: "session"
      IMAGE_COLLECTION: "image"
      SECRET_KEY: ""
      REDIS_URL: "redis:6379"
      TIME_LIVE_MINUTE_JWT: 1000
      TIME_EXPIRED_CACHE_MINUTE: 1
      ECHO_PORT: "8005"
    ports:
      - "8005:8000"
    depends_on:
      - postgres

  mongo:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      APP_MONGO_DB: "app"

  redis:
    image: redis
    ports:
      - "6380:6379"

  flyway:
    image: flyway/flyway
    command: "-url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=postgres -connectRetries=10 migrate"
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    depends_on:
      - postgres