version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESS_HOST: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgress/init_db:/docker-entrypoint-initdb.d

  golang:
    build:
      context: .
      dockerfile: ./docker/application/dockerfile
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESS_HOST: "postgres"
      POSTGRESS_PORT: 5432
    ports:
      - "8005:8000"
    depends_on:
      - postgres
