version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESS_HOST: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - ./docker/postgress/init_db:/docker-entrypoint-initdb.d
  golang:
    image: golang